# @Author: Guillaume de Matos <schlipak>
# @Date:   29-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 30-Aug-2016

dist: trusty
language: crystal
sudo: required
crystal:
  - latest
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libnotify-dev
before_install:
  - sudo apt-get update
  - sudo apt-get install python-gtk2-dev libdbus-1-dev libdbus-glib-1-dev
  - pip install dbus-python
  - cd /tmp
  - git clone https://github.com/halhen/statnot
  - cd statnot/
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - touch ~/.statusline.sh
  - python2 statnot &
script: crystal spec -v
