# @Author: Guillaume de Matos <schlipak>
# @Date:   29-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 30-Aug-2016

dist: trusty
language: crystal
sudo: required
crystal:
  - latest
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libnotify-dev
before_install:
  - sudo apt-get update
  - sudo apt-get install python-gtk2-dev python-gobject-2-dev libdbus-1-dev libdbus-glib-1-dev
  - pip install --upgrade pip
  - pip install dbus-python numpy
  - cd /tmp
  - wget https://cairographics.org/releases/py2cairo-1.10.0.tar.bz2
  - tar xf py2cairo-1.10.0.tar.bz2
  - cd py2cairo-1.10.0/
  - python2 ./waf configure --prefix=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/
  - python2 ./waf build
  - python2 ./waf install
  - cd /tmp
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0/
  - export PKG_CONFIG_PATH=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/pkgconfig
  - ./configure --prefix=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/
  - make
  - make install
  - cd /tmp
  - git clone https://github.com/halhen/statnot
  - cd statnot/
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - touch ~/.statusline.sh
  - python2 statnot &
script: crystal spec -v
