# @Author: Guillaume de Matos <schlipak>
# @Date:   29-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 30-Aug-2016

language: crystal
sudo: required
crystal:
  - latest
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libnotify-dev
before_install:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
