# @Author: Guillaume de Matos <schlipak>
# @Date:   29-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 30-Aug-2016

language: crystal
sudo: required
before_install:
  - "sudo apt-get install libnotify4"
  - "ls -l /usr/lib | grep 'notify.*so'"
  - "ls -lR /usr/lib | grep 'notify.*so'"
  - "ls -l /usr/local/lib | grep 'notify.*so'"
  - "ls -lR /usr/local/lib | grep 'notify.*so'"
