# @Author: Guillaume de Matos <schlipak>
# @Date:   29-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 30-Aug-2016

language: crystal
sudo: required
crystal:
  - latest
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libnotify-dev
before_install:
  - cd /tmp
  - git clone https://github.com/sboli/twmn.git
  - cd twmn/
  - sudo apt-get install qt4-qmake libqt4-dev libboost1.49-dev libdbus-1-dev libxext-dev libboost-program-options1.49-dev libboost-system1.49-dev
  - qmake
  - make
  - sudo make install
  - cd /tmp
  - rm -rf twmn/
  - twmnd &
  - sh -e /etc/init.d/xvfb start
  - sleep 3
