# @Author: Guillaume de Matos <schlipak>
# @Date:   29-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 30-Aug-2016

language: crystal
sudo: required
crystal:
  - latest
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
      - libgtk2.0-dev
      - libnotify-dev
before_install:
  - cd /tmp
  - git clone https://github.com/halhen/statnot
  - cd statnot/
  - sudo add-apt-repository ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install python2.7 python-gtk2-dev
  - sudo pip install dbus-python
  - sudo make install
  - cd /tmp
  - rm -rf statnot/
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - statnot &
