# @Author: Guillaume de Matos <schlipak>
# @Date:   28-Aug-2016
# @Email:  g.de.matos@free.fr
# @Last modified by:   schlipak
# @Last modified time: 29-Aug-2016

language: crystal
sudo: required
before_install: "sudo apt-get install libnotify-bin notify-osd"
